# Generated by Django 6.0.1 on 2026-01-26 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holder_name', models.CharField(max_length=100)),
                ('balance', models.FloatField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('atm_requested', models.BooleanField(default=False)),
                ('cheque_requested', models.BooleanField(default=False)),
                ('business_name', models.CharField(max_length=150)),
                ('overdraft_limit', models.FloatField(default=50000)),
                ('loan_limit', models.FloatField(default=200000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SavingsAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holder_name', models.CharField(max_length=100)),
                ('balance', models.FloatField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('atm_requested', models.BooleanField(default=False)),
                ('cheque_requested', models.BooleanField(default=False)),
                ('pin', models.IntegerField()),
                ('daily_limit', models.FloatField(default=20000)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
